name: Allure Report Generation

on:
  workflow_dispatch: # Trigger the workflow manually
    inputs:
      tags: # Input parameter for test scenario tags
        description: "Test scenario tags"
        required: true
        default: "smoke"

jobs:
  generate-allure-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Python 3 # Step to install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11 # Set the Python version to install

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "./requirements.txt"

      - name: Run tests with pytest # Step to run tests using pytest
        run: |
          python main.py

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
